name: 'Jekyll Actions Typescript/JS'
description: 'A GitHub Action to build and publish Jekyll sites to GitHub Pages without Docker'
inputs:
  jekyll_src:  
    description: 'The Jekyll website source directory'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
