name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - test-ts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache bundle files
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: tstest-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          tstest-${{ runner.os }}-gems-
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - uses: ./
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}