name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - test-ts

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.step1.outputs.jekyllSrc }}
      hash: ${{ steps.step1.outputs.jekyllHash }}
    steps:
    - uses: actions/checkout@v2
    - id: step1
      name: Find jekyll directory
      run: |
        JEKYLL_SRC=$(find . -path ./vendor/bundle -prune -o -name _config.yml -exec dirname {} \; | tr -d '\n')
        JEKYLL_HASH=$(ls -alR --full-time ${JEKYLL_SRC} | sha1sum)
        echo "::set-output name=jekyllSrc::${JEKYLL_SRC}"
        echo "::set-output name=jekyllHash::${JEKYLL_HASH}"
    - name: Cache bundle files
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: tstest-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          tstest-${{ runner.os }}-gems-
    - name: Cache jekyll files
      uses: actions/cache@v1
      with:
        path: ${{build.outputs.src}}/.jekyll-cache
        key: tstest-${{ runner.os }}-jekyll-${{build.outputs.hash}}
        restore-keys: |
          tstest-${{ runner.os }}-jekyll-
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - uses: ./
      with:
        jekyll_src: ${{build.outputs.src}}
    - name: Deploy
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site